name: log-cache

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: log-cache
  version: latest
- name: bosh-dns
  version: latest

addons:
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns

instance_groups:
- name: log-cache-scheduler
  azs:
  - z1
  - z2
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache-scheduler
    release: log-cache

- name: log-cache
  azs:
  - z1
  - z2
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache
    release: log-cache
    properties:
      egress_port: 8080
      health_addr: "localhost:6060"
      tls:
        ca_cert: "((log_cache.ca))"
        cert: "((log_cache.certificate))"
        key: "((log_cache.private_key))"
  - name: log-cache-gateway
    release: log-cache
  - name: log-cache-group-reader
    release: log-cache
    properties:
      port: 8084
  - name: log-cache-nozzle
    release: log-cache
    consumes:
      reverse_log_proxy: {from: reverse_log_proxy, deployment: loggregator}
    properties:
      logs_provider:
        tls:
          ca_cert: "((logs_provider.ca))"
          cert: "((logs_provider.certificate))"
          key: "((logs_provider.private_key))"
  - name: log-cache-expvar-forwarder
    release: log-cache
    properties:
      counters:
        # Log Cache
      - name: egress
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.Egress}}"
      - name: ingress
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.Ingress}}"
      - name: expired
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.Expired}}"

        # Nozzle
      - name: egress
        source_id: log-cache-nozzle
        addr: http://localhost:6061/debug/vars
        template: "{{.Nozzle.Egress}}"
      - name: ingress
        source_id: log-cache-nozzle
        addr: http://localhost:6061/debug/vars
        template: "{{.Nozzle.Ingress}}"
      - name: err
        source_id: log-cache-nozzle
        addr: http://localhost:6061/debug/vars
        template: "{{.Nozzle.Err}}"
      gauges:
        # Log Cache
      - name: cache-period
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.CachePeriod}}"
      - name: store-size
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.StoreSize}}"
      - name: total-system-memory
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.TotalSystemMemory}}"
      - name: available-system-memory
        source_id: log-cache
        addr: http://localhost:6060/debug/vars
        template: "{{.LogCache.AvailableSystemMemory}}"

variables:
- name: logs_provider
  type: certificate
  options:
    ca: loggregator_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth
    - server_auth
- name: log_cache_ca
  type: certificate
  options:
    is_ca: true
    common_name: log-cache
- name: log_cache
  type: certificate
  options:
    ca: log_cache_ca
    common_name: log-cache
    alternative_names:
    - log_cache
    - log-cache
    - logcache
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
