golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: dbb8e695-7cd4-4cb5-7f56-a2df5a4f4085
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/18d8a51c097f1b3957720a705fd2d00e8062e50cfe48ad1ac3e06b8bf234d5ee:
  size: 59768009
  object_id: 20922855-b2c4-4530-4b8c-44e6a132430b
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
golang-1.25-linux/288cfe8883218087eeb75040802f471670df0e64e5c4d360b68b0109830b9329:
  size: 59766306
  object_id: 186926af-0c2a-4cbd-4e9e-9b5975e0d5df
  sha: sha256:d7fa7f8fbd16263aa2501d681b11f972a5fd8e811f7b10cb9b26d031a3d7454b
golang-1.25-windows/b59a156693e6667d9a6f981dce2dc2a268d292bd94fa0ddb4fa4b756f535bbef:
  size: 67442664
  object_id: a8149f93-50c7-45f3-7935-d96c55daaa0c
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/d59b40b0d4a5b7f3359d943bcd143637163db0351db4038ba7a1a490a0a6fbec:
  size: 67437540
  object_id: 63358f4c-2a9b-4384-5fd1-e4b22398dd99
  sha: sha256:c18b46f6aa44dbfcd54a9db19dd2fcc5ad684819addcfcf968aa75dad89a89c8
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: 6706ac45-04f5-4f76-6f9e-7463e30880cc
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
