---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: log-cache-tls
  namespace: pas-system
spec:
  host: log-cache.pas-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
